account/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'account'
urlpatterns = [
    url(r'login', views.login_view, name='login_view'),
    url(r'logout', views.logout_view, name='logout_view'),
    url(r'register', views.register, name='register'),
    url(r'change', views.change, name='change'),
    url(r'^', views.login_view, name='index'),

]

civic_marketplace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import landing

urlpatterns = [
    url(r'^account/', include('account.urls'), name='account'),
    url(r'^dashboard/', include('dashboard.urls'), name='dashboard'),
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url(r'^', include('landing.urls'), name='landing')
]

dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^jobdetail/(?P<job_id>[0-9]+)', views.jobdetail, name='jobdetail'),
    url(r'^addjob', views.addjob, name='addjob'),
    url(r'^managejobs', views.managejobs, name='managejobs'),
    url(r'^manage_one_job/(?P<job_id>[0-9]+)', views.manage_one_job, name='manage_one_job'),
    url(r'^participate', views.participate, name='participate'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^review', views.review, name='review'),
    url(r'^user/(?P<user_id>[0-9]+)', views.public_profile, name='user'),
    url(r'^', views.index, name='index'),
]

landing/urls.py
from django.conf.urls import url
from . import views

app_name = 'landing'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

landing/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

from dashboard.models import Job

def index(request):
    jobs = Job.objects.all()
    if request.user.is_authenticated:
        user = request.user
    else: user = None
    return render(request, 'landing/index.html', {'jobs':jobs, 'user':  user})

landing/templates/landing/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DoGood.world - A Marketplace for Social Good</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Bootstrap Core CSS -->
	<link href="{% static 'landing/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<link href="{% static 'landing/css/landing.css' %}" rel="stylesheet">
	<link href="{% static 'dashboard/css/dashboard.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
	{% include "landing/navbar.html" %}

    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>DoGood.world</h1>
            <h3>A Marketplace for Social Good</h3>
            <br>
			<a href="{% url 'account:login_view' %}" class="btn btn-dark btn-lg">Make a Difference</a>
        </div>
    </header>

    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    <section id="services" class="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-12 col-lg-offset-0">
                    <h2>Make the world a better place.</h2>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <h3>Contribute your expertises</h3>
                            <hr class="small">
                            <div class="col-md-12 col-sm-6">
                                <div class="service-item">
                                    <span class="fa-stack fa-4x">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-cloud fa-stack-1x text-primary"></i>
                                    </span>
                                    <p>Make impact, use your skills, explore how you can make a difference.</p>
                                    <a href="{% url 'account:login_view' %}" class="btn btn-default btn-lg">Explore Opportunities</a>
                                </div>
                            </div>
						</div>
                        <div class="col-md-6 col-sm-6">
                            <h3>Launch your next event</h3>
                            <hr class="small">
                            <div class="col-md-12 col-sm-6">
                                <div class="service-item">
                                    <span class="fa-stack fa-4x">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-cloud fa-stack-1x text-primary"></i>
                                    </span>
                                    <p>Find latents, manage volunteers, connect to people who care.</p>
                                    <a href="{% url 'account:login_view' %}" class="btn btn-default btn-lg">Publish Your Events</a>
                                </div>
                            </div>
						</div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <section id="portfolio" class="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h2 stype="color:#0088cc">Trending Opportunities</h2>
                    <hr>
                {% for job in jobs %}
                    <div class="col-md-4">
                        <a href="{% url 'dashboard:jobdetail' job.id %}?user_id=-1">
                        <div class="cover-img-div">
                            <img class="img-portfolio img-responsive" src="{{ job.thumb }}">
                        </div>
                        <h4>{{ job.title }}</h4>
                        </a>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
      <section id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h4><strong>Contact Us</strong></h4>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i><a href="mailto:name@example.com">name@example.com</a></li>
                    </ul>
                    <hr>
                    <p>Copyright &copy; DoGood.world 2017</p>
                </div>
            </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
      </section>
    </footer>
</body>

</html>

landing/templates/landing/navbar.html
<!DOCTYPE html>
{% load static %}
<nav class="navbar navbar-default navbar-faded navbar-fixed-top">
	<div class="container-fluid">
		<!--
		<div class="navbar-header">
  		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#collapseContent" aria-controls="collapseContent" aria-expanded="false">
	    <span class="navbar-toggler-icon"></span>
	    </button>
		</div>
		-->
        <a class="navbar-brand" href="{% url 'landing:index' %}">DoGood.world</a>
		<div class="collapse navbar-collapse" id="collapseContent">
            <ul class="nav navbar-nav navbar-right">
                {% if user.id is not None %}
                <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:index' %}">Hello {{user.username}}!</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'account:logout_view' %}">Log Out</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'account:index' %}">Log In</a></li>
                {% endif %}
            </ul>
    	</div>
  	</div>
</nav>