account/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'account'
urlpatterns = [
    url(r'login', views.login_view, name='login_view'),
    url(r'logout', views.logout_view, name='logout_view'),
    url(r'register', views.register, name='register'),
    url(r'change', views.change, name='change'),
    url(r'^', views.login_view, name='index'),

]

civic_marketplace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import landing

urlpatterns = [
    url(r'^account/', include('account.urls'), name='account'),
    url(r'^dashboard/', include('dashboard.urls'), name='dashboard'),
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url(r'^', include('landing.urls'), name='landing')
]

dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^jobdetail/(?P<job_id>[0-9]+)', views.jobdetail, name='jobdetail'),
    url(r'^addjob', views.addjob, name='addjob'),
    url(r'^managejobs', views.managejobs, name='managejobs'),
    url(r'^manage_one_job/(?P<job_id>[0-9]+)', views.manage_one_job, name='manage_one_job'),
    url(r'^participate', views.participate, name='participate'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^review', views.review, name='review'),
    url(r'^user/(?P<user_id>[0-9]+)', views.public_profile, name='user'),
    url(r'^', views.index, name='index'),
]

dashboard/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django import forms
from datetime import datetime
from datetimewidget.widgets import DateTimeWidget

from account.models import User, Skill, Cause

class Job(models.Model):
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField()
    description = models.TextField()
    identity = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    start_time = models.DateTimeField(default=timezone.now, blank=True)
    end_time = models.DateTimeField(default=timezone.now, blank=True)
    thumb = models.URLField(blank=True)
    past = models.BooleanField(default=False)
    def __str__(self):
        return '%s' % (self.title)

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ('thumb', 'publisher', 'title', 'description', 'location', 'start_time', 'end_time')
        widgets = {
            'start_time': DateTimeWidget(attrs={'id':"start_time"}, usel10n=True, bootstrap_version=3),
            'end_time': DateTimeWidget(attrs={'id':"end_time"}, usel10n=True, bootstrap_version=3),
            'title': forms.Textarea(attrs={'rows': 1}),
            'description': forms.Textarea(attrs={'rows': 5}),
        }

class Involve(models.Model):
    participant = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    review = models.TextField(default='')
    score = models.PositiveSmallIntegerField(default=0)

class JobSkill(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)

class JobCause(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    cause = models.ForeignKey(Cause, on_delete=models.CASCADE)

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.messages import error, success
from django.db.models import Avg
from django import forms
from mimetypes import guess_extension
#from google.cloud import storage
from django.contrib.auth.decorators import login_required
from datetimewidget.widgets import DateTimeWidget
import random

from .models import Job, Involve, JobCause, JobSkill, JobForm
from account.models import User, UserIdentity, Cause, Skill, UserCause, UserSkill, PreferredTime, UserPreferredTime

def get_user_by_id(request):
    try:
        user = User.objects.get(id=request.session['user_id'])
    except (KeyError, User.DoesNotExist):
        error(request, 'User does not exist.')
        return None
    return user

def get_job_by_id(request):
    if 'job_id' not in request.session:
        error(request, 'Job does not exist.')
        return None
    try:
        job = Job.objects.get(id=request.session['job_id'])
    except (KeyError, Job.DoesNotExist):
        error(request, 'Job does not exist.')
        return None
    return job

def get_involve(job, user):
    return Involve.objects.filter(job=job, participant=user)

#@login_required(login_url='/account/')
def index(request):
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    past_jobs = []
    current_jobs = []
    involves = Involve.objects.filter(participant=user.id)
    for involve in involves:
        job = Job.objects.get(id=involve.job.id)
        if job.past: past_jobs.append(job)
        else: current_jobs.append(job)

    recommended_jobs = []  
    for job in Job.objects.filter(past=False):
        if job not in past_jobs and job not in current_jobs:
            w_cause = w_skill = 0
            causes = Cause.objects.filter(usercause__user=user)
            for jobcause in JobCause.objects.filter(job=job):
                if jobcause.cause in causes: w_cause += 1
            skills = Skill.objects.filter(userskill__user=user)
            for jobskill in JobSkill.objects.filter(job=job):
                if jobskill.skill in skills: w_skill += 1
            recommended_jobs.append((job, w_cause + w_skill))
    recommended_jobs.sort(key=lambda x: x[1], reverse=True)
     
    return render(request, 'dashboard/index.html', { 
        'user':user, 'past_jobs':past_jobs, 'current_jobs':current_jobs,
        'recommended_jobs':[j[0] for j in recommended_jobs],
    })

def managejobs(request):
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    upcoming_jobs = Job.objects.filter(publisher=user, past=False)  
    past_jobs = Job.objects.filter(publisher=user, past=True)
    return render(request, 'dashboard/managejobs.html', { 
        'user':user, 'upcoming_jobs':upcoming_jobs, 'past_jobs':past_jobs
    })

def manage_one_job(request, job_id):
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    try:
        job = Job.objects.get(id=job_id)
    except (KeyError, Job.DoesNotExist):
        error(request, 'The job does not exist.')
        return redirect('dashboard:index')
    request.session['job_id'] = job_id
    return render(request, 'dashboard/manage_one_job.html', {
        'user':user, 'job':job, 'job_skills':Skill.objects.filter(jobskill__job=job), 'job_causes':Cause.objects.filter(jobcause__job=job),
        'skills':Skill.objects.all(), 'causes':Cause.objects.all(),
        'involved_users':User.objects.filter(involve__job=job),
        'job_form':JobForm(instance=job)
    })

def jobdetail(request, job_id):
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    # For now allowing every job to be seen, add a check if it's not true
    try:
        job = Job.objects.get(id=job_id)
    except (KeyError, Job.DoesNotExist):
        error(request, 'The job does not exist.')
        return redirect('dashboard:index')
    request.session['job_id'] = job_id
    try:
        involve = Involve.objects.get(job=job, participant=user)
    except (KeyError, Involve.DoesNotExist):
        involve = None
    other_users = User.objects.filter(involve__job=job)[:10]
    for other_user in other_users:
        t = Involve.objects.filter(participant=user).aggregate(Avg('score'))['score__avg']
        #if t is None: other_user.score = 0
        #else: other_user.score = int(t)
        #TODO: filter None
        other_user.score = int(5)
    return render(request, 'dashboard/jobdetail.html', {
        'involve':involve, 'user':user, 'job':job, 'skills':Skill.objects.filter(jobskill__job=job), 'causes':Cause.objects.filter(jobcause__job=job),
        'other_users':other_users
    })

def participate(request):
    if request.method == 'GET':
        return redirect('dashboard:index')
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    job = get_job_by_id(request)
    if job is None: return redirect('account:index')
    del request.session['job_id']
    participate = get_involve(job, user)
    if len(participate) == 0:
        participate = Involve(job=job, participant=user)
        participate.save()
        return redirect('dashboard:index')
    else:
        participate[0].delete()
        return redirect('dashboard:index')

def handle_uploaded_file(f, job_id):
    content_type = guess_extension(f.content_type)
    filename = 'job_cover_%d%s' % (job_id, content_type)
    client = storage.Client()
    bucket = client.get_bucket('catalyst-market.appspot.com')
    blob = bucket.get_blob('jobs_cover_img/' + filename)
    if blob is None: blob = bucket.blob('jobs_cover_img/' + filename)
    for chunk in f.chunks():
        blob.upload_from_string(chunk)
    return blob.public_url

def addjob(request):
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    causes = Cause.objects.all()
    skills = Skill.objects.all()
    user_identities = [str(user.username)] + [str(ui.identity) for ui in UserIdentity.objects.filter(user=user)]
    if request.method == 'GET':
        return render(request, 'dashboard/addjob.html', {'user':user, 'causes':causes, 'skills':skills, 'user_identities':user_identities, 'job_form':JobForm()})
    if 'job_id' in request.POST:
        job = JobForm(request.POST, instance=Job.objects.get(id=request.POST['job_id']))
    else:
        job = JobForm(request.POST)
    if job.is_valid():
        job = job.save()
    else:
        error(request, job.errors)
        return redirect('dashboard:managejobs')
    if 'cover' in request.FILES and len(request.FILES['cover']) > 0:
        print request.FILES['cover']
        img = handle_uploaded_file(request.FILES['cover'], job.id)
    else:
        img = 'landing/img/portfolio-%d.jpg' % random.randint(1, 4)
    job.thumb = img
    job.save()

    JobSkill.objects.filter(job=job).delete()
    for skill in request.POST.getlist('skills'):
        jobskill = JobSkill(job=job, skill=Skill.objects.get(name=skill))
        jobskill.save()
    JobCause.objects.filter(job=job).delete()
    for cause in request.POST.getlist('causes'):
        jobcause = JobCause(job=job, cause=Cause.objects.get(name=cause))
        jobcause.save()
    return redirect('dashboard:managejobs')

def profile(request):
    user = get_user_by_id(request)
    if user is None: return redirect('account:index')
    causes = Cause.objects.all()
    user_causes = causes.filter(usercause__user=user)
    skills = Skill.objects.all()
    user_skills = skills.filter(userskill__user=user)
    user_identities = UserIdentity.objects.filter(user=user)
    return render(request, 'dashboard/profile.html', {
        'user':user, 'causes':causes, 'user_causes':user_causes, 'skills':skills, 'user_skills':user_skills, 'user_identities':user_identities,
        'preferred_times':PreferredTime.objects.all(),
        'user_preferred_times':PreferredTime.objects.filter(userpreferredtime__user=user)
    })

def public_profile(request, user_id):
    user = User.objects.get(id=user_id)
    causes = Cause.objects.filter(usercause__user=user)
    skills = Skill.objects.filter(userskill__user=user)
    involves = Involve.objects.filter(participant=user)
    return render(request, 'dashboard/public_profile.html', {'user':user, 'skills':skills, 'causes':causes, 'involves':involves})

def review(request):
    if request.method == 'GET':
        user = User.objects.get(id=request.GET['user_id'])
        job = Job.objects.get(id=request.GET['job_id'])
        involve = Involve.objects.get(participant=user, job=job)
        return render(request, 'dashboard/review.html', {'user':user, 'job':job, 'involve':involve})
    user = User.objects.get(id=request.POST['user_id'])
    job = Job.objects.get(id=request.POST['job_id'])
    involve = Involve.objects.get(participant=user, job=job)
    involve.review = request.POST['review']
    involve.score = request.POST['score']
    involve.save()
    return redirect('dashboard:manage_one_job', request.POST['job_id'])

dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CataLyst - Dashboard</title>
    <!-- Bootstrap Core CSS -->
	<link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
	<link href="{% static 'dashboard/css/dashboard.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
</head>

<body>
	{% include "landing/navbar.html" %}
	<div class="container-fluid row">
	  	<div class="col-md-2">
            <ul class="nav flex-column">
				<hr>
                <li><a class="nav-link active" href="{% url 'dashboard:index' %}">Overview</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:addjob' %}">Publish an Event</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:managejobs' %}">Manage Events</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:profile' %}">My Profile</a></li>
            </ul>
	  	</div>

        <div class="col-md-10">
			{% if messages %}
				<ul class="messages">
   					{% for message in messages %}
			    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
				        	{{ message }}
					    </li>
				    {% endfor %}
				</ul>
			{% endif %}
	  		<div class="row text-center">
                <hr class="small">
                <h3>Participating</h3>
                {% for job in current_jobs %}
                    {% if forloop.first %}<div class="row">{% endif %}
                    <div class="col-md-3  text-center">
                        <a href="{% url 'dashboard:jobdetail' job.id %}">
							<div class="cover-img-div"><img class="img-portfolio img-responsive" src="{{ job.thumb }}"></div>
							<h4>{{ job.title }}</h4>
	                    </a>
                   </div>
                   {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
                   {% if forloop.last %}</div>{% endif %}
               {% endfor %}
			</div>
	  		<div class="row text-center">
                <hr class="small">
                <h3>These May Interest You</h3>
                {% for job in recommended_jobs %}
                    {% if forloop.first %}<div class="row">{% endif %}
                    <div class="col-md-3 text-center">
						<a href="{% url 'dashboard:jobdetail' job.id %}">
							<div class="cover-img-div"><img class="img-portfolio img-responsive" src="{{ job.thumb }}"></div>
						<h4>{{ job.title }}</h4>
						</a>
                    </div>
                    {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
                    {% if forloop.last %}</div>{% endif %}
                {% endfor %}
			</div>
	  		<div class="row text-center">
                <hr class="small">
                <h3>Participated Events</h3>
                {% for job in past_jobs %}
                    {% if forloop.first %}<div class="row">{% endif %}
                    <div class="col-md-3  text-center">
                        <a href="{% url 'dashboard:jobdetail' job.id %}">
							<div class="cover-img-div"><img class="img-portfolio img-responsive" src="{{ job.thumb }}"></div>
							<h4>{{ job.title }}</h4>
	                    </a>
                   </div>
                   {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
                   {% if forloop.last %}</div>{% endif %}
               {% endfor %}
			</div>
        </div>
    </div>
  </div>
</body>
</html>

dashboard/templates/dashboard/jobdetail.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CataLyst - Dashboard</title>
    <!-- Bootstrap Core CSS -->
	<link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
	<link href="{% static 'dashboard/css/dashboard.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="{% static 'dashboard/js/bootstrap-rating-input.min.js' %}"></script>
</head>

<body>
	{% include "landing/navbar.html" %}

    <div class="container-fluid">
        <div class="row">
	        <div class="col-md-2">
            <ul class="nav flex-column">
				<hr>
                <li><a class="nav-link active" href="{% url 'dashboard:index' %}">Overview</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:addjob' %}">Publish an Event</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:managejobs' %}">Manage Events</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:profile' %}">My Profile</a></li>
            </ul>
   	        </div>
			<hr>
            <div class="col-md-6">
	        	<div class="row">
           			<div class="col-md-6 text-center">
						<div class="cover-img-div"><img class="img-portfolio img-responsive" src="{{ job.thumb }}"></div>
	                	<h3>{{ job.title }}</h3>
					</div>
            		<div class="col-md-6">
                		<h4>Released by: {{ job.identity }}</h4>
						<br>
                        <h4>Start: {{ job.start_time }}</h4>
                        <h4>End: {{ job.end_time }}</h4>
                        <h4>Location: {{ job.location }}</h4>
						<br>
						{% if not job.past %}
       			     	<form id="part-form" action="{% url 'dashboard:participate' %}" method="post" role="form">
            			{% csrf_token %}
							<input type="submit" id="participate-submit" tabindex="1" class="btn btn-primary" value="{% if involve == None %}Participate{% else %}Unparticipate{% endif %}">
                			<input type="text" id="user_id" name="user_id" tabindex="2" style="display:none" value="{{ user.id }}">
                			<input type="text" id="job_id" name="job_id" tabindex="3" style="display:none" value="{{ job.id }}">
                		</form>
						{% endif %}
                    </div>
				</div>
				<hr>
	        	<div class="row">
            		<div class="col-md-12">
	                	<h4>{{ job.description }}</h4>
					</div>
                	<div class="col-md-12">
					<br>
                	<h5>Categories: </h5>
	                	{% for cause in causes %}
							<span>&nbsp;&nbsp; {{ cause.name }} &nbsp;&nbsp;</span>
                    	{% endfor %}
                	</div>
                	<div class="col-md-12">
                	<h5>Preferred skills: </h5>
                    	{% for skill in skills %}
							<span>&nbsp;&nbsp; {{ skill.name }} &nbsp;&nbsp;</span>
                    	{% endfor %}
                	</div>
            	</div>
            	<hr>
				{% if involve != None and job.past %}
					<h4>Reviews</h4>
	                <input type="number" name="score" id="score" class="rating" value="{{ involve.score }}"/>
					<h5>{{ involve.review }}</h5>
				{% endif %}
				
            </div>
            <div class="col-md-4 col-xs-12">
				<h4>They are also going:</h4><br>
				<div class="row">
              	{% for other_user in other_users %}
                    <div class="col-md-4 col-xs-6 text-center">
                    	<div class="avatar-div">
                    		<img class="img-portfolio img-responsive center-block" src="{{ other_user.avatar }}">
                   		</div>
                    	<h5><a href="{% url 'dashboard:user' other_user.id %}">{{ other_user.username }}</a></h5>
						<input type="number" name="score" id="score" class="rating" value="{{ other_user.score }}"/>
                    </div>
               	{% endfor %}
        		</div>
        	</div>
        </div>
    </div>
</body>

</html>

dashboard/templates/dashboard/manage_one_job.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CataLyst - Dashboard</title>
    <!-- Bootstrap Core CSS -->
	<link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
	<link href="{% static 'dashboard/css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {{ job_form.media }}
</head>

<body>
	{% include "landing/navbar.html" %}

    <div class="container-fluid">
        <div class="row">
	        <div class="col-md-2">
            <ul class="nav flex-column">
				<hr>
                <li><a class="nav-link" href="{% url 'dashboard:index' %}">Overview</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:addjob' %}">Publish an Event</a></li>
                <li><a class="nav-link active" href="{% url 'dashboard:managejobs' %}">Manage Events</a></li>
                <li><a class="nav-link" href="{% url 'dashboard:profile' %}">My Profile</a></li>
            </ul>
   	        </div>
        	{% if messages %}
            	{% for message in messages %}
                	<p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            	{% endfor %}
        	{% endif %}
            <form id="part-form" action="{% url 'dashboard:addjob' %}" method="post" role="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-4 col-md-offset-1">
				<hr>
                {% load widget_tweaks %}
                {% for field in job_form %}
                    {% if field.name == "thumb" %}
	  			    <div class="row">
				        <div class="col-md-8 text-center">
                	        <div class="form-group">
						    <div class="cover-img-div">
                    		    <img class="img-portfolio img-responsive center-block" src="{{ field.value }}">
						    </div>
						    </div>
				        </div>
  				        <div class="col-md-4 text-center">
                	        <div class="form-group">
                   		        <label class="btn btn-primary btn-file">Change Cover Picture<input type="file" id="cover" name="cover" style="display:none;"></label>
					        </div>
					        <label class="btn btn-info">
                       	        <input type="checkbox" name="done" {% if job.past %}checked{% endif %} style="display:none;">This event has finished
                   	        </label>
					    </div>
				    </div>
                    {% elif field.name != "publisher" %}
                    <div class="form-group">
                    <div class="row">
                    <label class="col-md-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                        <div class="col-md-10">
                           {{ field|attr:"class:form-control" }}
                           {% if field.help_text %}
                               <p class="help-block"><small>{{ field.help_text }}</small></p>
                           {% endif %}
                        </div>
                    </div>
                    </div>
                    {% endif %}
                {% endfor %}

	            <div class="row">
            		<hr>
                	<h4>Registered Users</h4>
	                	{% for involved_user in involved_users %}
							<div class="col-md-4 text-center">
								<div class="avatar-div">
									<img class="img-portfolio img-responsive center-block" src="{{ involved_user.avatar }}">
								</div>
								<h5><a href="{% url 'dashboard:user' involved_user.id %}">{{ involved_user.username }}</a></h5>
								<a href="{% url 'dashboard:review' %}?user_id={{ involved_user.id}}&job_id={{ job.id }}"><label class="btn btn-primary">Write a review</label></a>
                        	</div>
                    	{% endfor %}
            	</div>
            </div>
            <div class="col-md-4 col-md-offset-1">
	            <div class="row">
                	<div class="col-md-12">
            		<hr>
                	<h4>Categories</h4>
	                	{% for cause in causes %}
                        	<div class="col-md-3">
								<label class="button-check">
                                	<input type="checkbox" name="causes" value="{{ cause.name }}" {% if cause in job_causes %}checked{% endif %}> 
                                	<h5>{{ cause.name }}</h5>
                            	</label>
                        	</div>
                    	{% endfor %}
                	</div>
            	</div>
            	<div class="row">
            	<hr>
                	<div class="col-md-12">
                	<h4>Preferred skills</h4>
                    	{% for skill in skills %}
                        	<div class="col-md-3">
								<label class="button-check">
                                	<input type="checkbox" name="skills" value="{{ skill.name }}" {% if skill in job_skills %}checked{% endif %}> 
                                	<h5>{{ skill.name }}</h5>
                            	</label>
                        	</div>
                    	{% endfor %}
                	</div>
            	</div>
            	<hr>
				<input type="submit" id="participate-submit" tabindex="1" class="btn btn-primary" value="Update">
                <input type="text" id="publisher" name="publisher" tabindex="2" style="display:none" value="{{ user.id }}">
                <input type="text" id="job_id" name="job_id" tabindex="3" style="display:none" value="{{ job.id }}">
                <input type="text" id="identity" name="identity" tabindex="3" style="display:none" value="{{ job.identity }}">
                </form>
            </div>
        </div>
    </div>
</body>

</html>